/** Compact, reusable instructions injected into MCQ generation. */
export const EXAMFIG_DIAGRAM_SKILL = `
EXAMFIG DIAGRAM SKILL:
You may add one educational diagram when it materially improves the question. Return a JSON-encoded semantic examfig DiagramSpec string in the 'diagram' field; use null when no diagram is appropriate. Never return SVG, pixel coordinates, or hand-drawn paths. The decoded spec must include 'type' and a concise 'accessibleDescription' for screen readers. Use the narrowest type:
- math: function-graph (y=f(x)), data-plot (statistics), polar-graph, parametric-graph, slope-field, unit-circle, supply-demand, table
- physics: free-body, inclined-plane, motion-map, circuit, field-map, ray-diagram, wave-diagram, energy-chart
- chemistry: particle-diagram, lewis-structure, molecular-geometry, energy-profile, titration-curve, spectra-plot, electrochemical-cell, apparatus-schematic
- biology/environment: process-diagram, cell-diagram, genetic-cross, pedigree, phylogenetic-tree, experimental-setup, population-curve, food-web, resource-flow, map
Prefer semantic fields such as 'expression', 'direction', 'angleDegrees', 'points', 'nodes', and 'edges'; do not micromanage layout. Use safe math expressions only (for example 'x^2', 'sin(x)'). Keep labels short and put explanations in the question text. When a diagram is included, make the stem and answer choices more concise than a comparable non-diagram question: let the visual carry relationships, labels, and values, and do not repeat information that is already clear from the diagram. Keep enough text to establish context and the task. The diagram must directly support the tested concept, stay within the unit scope, and be monochrome/print-safe.
If you create a diagram, JSON.stringify the spec and pass that string as the tool's 'spec' input to 'validateExamfigDiagram' before finalizing it when that tool is available. The application parses and validates the final spec before persistence. If validation fails, fix the semantic JSON; never patch SVG. Use 'diagram: null' when a diagram would not add clear instructional value.`;
